//
//  RecipeModel.swift
//  CookingRecipe
//
//  Created by Al-Amin on 2023/06/06.
//

import Foundation


enum Category: String, CaseIterable, Identifiable {
    var id: String { self.rawValue }
    case breakfast = "Breakfast"
    case soup = "Soup"
    case salad = "Salad"
    case appetizer = "Appetizer"
    case main = "Main"
    case side = "Side"
    case dessert = "Dessert"
    case snack = "Snack"
    case drink = "Drink"
}

struct Recipe: Identifiable {
    let id = UUID()
    let name: String
    let image: String
    let description: String
    let ingredients: String
    let directions: String
    let category: Category.RawValue
    let datePublished: String
    let url: String
}

extension Recipe {
    static let all: [Recipe] = [
        Recipe(name: "Sushi", image: "https://images.pexels.com/photos/1639564/pexels-photo-1639564.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Breakfast", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Blueberry Farro Grain Bowl", image: "https://images.pexels.com/photos/724216/pexels-photo-724216.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Breakfast", datePublished: "2022-03-03", url: ""),
        Recipe(name: "BLUEBERRY-BANANA WRAPS", image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg", description: "Fresh blueberries and the sweetness of ripe bananas come together in perfect unison in these incredible wraps, which also feature celery, mint, spinach, and walnuts.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Soup", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Sushi", image: "https://images.pexels.com/photos/376672/pexels-photo-376672.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Salad", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Sushi", image: "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Appetizer", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Sushi", image: "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Soup", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Sushi", image: "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Drink", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Sauces", image: "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Salad", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Burger", image: "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Breakfast", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Stake", image: "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Breakfast", datePublished: "2022-03-03", url: ""),
        Recipe(name: "Swarma", image: "https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg", description: "Blueberries bring refreshing bursts of sweetness to this colorful bowl. Farro, an ancient grain and a cousin of modern wheat berries, makes a satisfying base. For a gluten-free version, you can use sorghum in place of farro.", ingredients: "½ cup dry farro 1 cup fresh blueberries, 1 cup fresh or thawed frozen corn, 1 cup halved cherry tomatoes, 1 cup finely chopped red or orange bell pepper, 1 small bulb fennel, trimmed and shaved, 1 scallion, thinly sliced, 8 to 10 fresh basil leaves, finely chopped, 2 tablespoons white rice vinegar, Sea salt and freshly ground black pepper, to taste, 1 tablespoon toasted pine nuts (optional)",
               directions: "In a medium saucepan combine farro and 1½ cups water. Bring to boiling; reduce heat. Cover and simmer 15 to 20 minutes or until farro is just tender. Drain any excess water. Transfer farro to a large bowl; let cool.To cooled farro, add the next seven ingredients (through basil). Add vinegar and season with salt and black pepper; toss to combine. If desired, garnish with pine nuts.", category: "Snack", datePublished: "2022-03-03", url: "")
    ]
}
